### ISSUE TITLE
`-vet` is mad!

### ISSUE THREAD

**Issue by ftphikari** [DaseinPhaos/pdb#2]
> modStream.odin(21:5) 'modHeader' declared but not used
cvtRecord.odin(4:8) 'strings' declared but not used
hashTable.odin(3:8) 'log' declared but not used
modStream.odin(5:8) 'strings' declared but not used
msf.odin(3:8) 'fmt' declared but not used
peFile.odin(7:8) 'mem' declared but not used
stackTrace.odin(2:8) 'log' declared but not used

**Comment by DaseinPhaos** [comment]
fixed in https://github.com/DaseinPhaos/pdb/commit/9139d71da187e3f4fb2a9901fc68dfa8d8d6a6ac
